### PR TITLE
feat: Change time & Attributes for Elements in Settings

### PR DESCRIPTION
**Pull request by iLollek**
**ATTRIBUTE LOADER FOR SETTINGS ELEMENTS IS NOT FINISHED YET!**
I will work on this tomorrow. I'm way too tired. I'll also probably revise the code here and there -- so feel free to leave comments for everything that might seem unusual.

However, changing the time works. As requested in Ticket no. #58, you can now change from 24hr format (12:33) to 12 hr format (9:31 AM) - also live update

### CODE REVIEW

**Comment by kawapure** [comment]
image

Commits from your previous PR are also included. I recommend you correct this ASAP by starting a new branch based off of the head of the main repository, then remake the PR from that branch. Otherwise, they will be repeated over here when we come to merge the PR. In the future, you should always make PRs like this.

This is completely a GitHub UX issue, so I don't blame you for not paying much attention.

**Comment by iLollek** [comment]
I created a new Branch on my fork: ticket-58

**Comment by kawapure** [comment]
> I created a new Branch on my fork: ticket-58

All changes that you have made here haven't been migrated over, and I don't believe that it's possible to change the branch a PR on GitHub uses once the PR is opened. However, instead of reopening the PR, you can reset your repo on main, apply the commits you made recently, and push that (maybe you'll need to force push).

In command format, that's something like:

```bash
git remote add upstream https://github.com/not-nullptr/Aerochat
git checkout main
git fetch upstream
git log # To see commit hashes
git reset --hard upstream/main
git cherry-pick <commit-hash> # For each of your new commits
git push origin

**Comment by iLollek** [comment]
Replaced by https://github.com/not-nullptr/Aerochat/pull/63

**Pull request closed without merging**
